version: "3"
services:

  discordlanguagegaming:
    build: .
    env_file: discordlanguagegaming.env
    restart: always

    # use custom logger:
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://127.0.0.1"
        tag: "discordlanguagegaming"
